name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # deploy when pushing to main branch

permissions:
  contents: write  # required for GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: stable

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get
        working-directory: kenyandictionaryapp

      # Step 4: Build Flutter web app with Supabase keys
      - name: Build Flutter Web
        run: flutter build web --release \
          --base-href /kenyandictionaryapp/ \
