name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Step 3: Build Flutter Web
      - run: flutter build web --release

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
